spring:
  datasource:
    # mybatis_plus 配置执行 SQL 分析打印，需要改变 driver-class-name，url 参数，（未配置版本——prod）
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://192.168.8.131:32768/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCpExample
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

