server:
  port: 9013
spring:
  profiles:
    active: dev
    include: mybatisPlus
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接


# 无需登陆，可以直接访问的url
ignored:
  urls:
    - /oauth/login
    - /test/**
    - /oauth/captchaImage
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /**/*.html

# 不会进行限流的接口：支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /oauth/captchaImage
  # 短信接口
  sms:
    - /sms
  # 邮箱接口
  email:
    - /email
  # 其他接口
  urls:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /**/*.html

# 限流
yat:
  # 全局限流
  rate:
    limit:
      enable: true
      # 每1秒内
      timeout: 1
      # 总限制200个请求
      limit: 200
  # IP限流
  ip:
    second:
      limit:
        enable: true
        # 每 1秒内
        timeout: 1
        # 每个ip限制20个请求
        limit: 20
  cache:
    # 过期时间单位 支持day、hour、minute对应天、小时、分钟
    unit: day
    # 过期时间 永久不过期设为-1
    time: 15

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAOC5FjXCknqDK9HbZHRcmc8rhxrZ3zIj6ZUF8AmXX2jXuF+qZKjC+/V0zCtm0IRhxGKEYim6tqOi3HoDT6a4PFB4ia0osoBuu0WYFwVdrWEHS/Vpolwmv7WJdyhSCXv6ontEUjS4rgNX67EVe+omdeFxZeQshqDMd9WMm6eFJQ03AgMBAAECgYBRxujvLVwymxNSLf1zXtNWEaf7vHc9ftYctelxBBXjSEU/AvnYdAROgW9fB+4vjohxtW0ndFvMVpLXD+dnazn+/AD5sdQAfgXWS2xHXEjJXJZ2ANVNU79a0bM2JyDZB8xJaHLluIt38yOx9RwkdBy7FKSCXKc/4bNZjmoBxOTCmQJBAPh/Xd7JhwqF/ANuLZcpy3W2mXeAPRD7dFR+Jv9jUHB8IbV1IYbXlzwTpMpRZdWI7k2UbwlL+3EmGYcLL/OeYNMCQQDngfeU5wchhhSSieuCdSPK+Gs06xBg7lDjletYpkaVOV5erKlyglYC4UdE+KwCKrDaKhx+KaXfW7QqtZg+k8ONAkEAgZXp3cQ6J8K3KRLLs4iYEUqnvSmirrhycZ1XuNaRnBcffQEX+rlypGGaDedks3Y0z0AYp0B4Xwj/Ru0OlHyDAQJBAJ/Q7tNSMXAJGYaXw4cJyq3BlHCxnVrs6dZSlmdaUfuN4QHGfCtaonnWfta0PDo6sl/JFmZZ5fItYlDhj7oTU7kCQQCrYe1VBxJPfEl12FazVwot7Dlx8ZGgnw6XfXrquH5BZdRn0AfyNrB9IlYW4R891OZiQi7N2xzQhneolW1D2Iel
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDguRY1wpJ6gyvR22R0XJnPK4ca2d8yI+mVBfAJl19o17hfqmSowvv1dMwrZtCEYcRihGIpurajotx6A0+muDxQeImtKLKAbrtFmBcFXa1hB0v1aaJcJr+1iXcoUgl7+qJ7RFI0uK4DV+uxFXvqJnXhcWXkLIagzHfVjJunhSUNNwIDAQAB


jwt:
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 过期时间 单位：秒
  expire: 3600
  online:
    # 存在redis中，在线用户的key的前缀
    keyPrefix: 'online:token:'
  # 前端token配置；例如：Authorization：'Bearer token值'
  web:
    # 存储在前端请求头里的key
    header: Authorization
    # 存储在前端token的前缀
    tokenPrefix: 'Bearer '

#登录图形验证码有效时间：秒
loginCode:
  expiration: 120
