server:
  port: 9334

# ---------------------------- Minio ----------------------------
minio:
  endpoint:
    enable: true
    name: minio-endpoint
  url: http://minio.yatxuan.cn
  access-key: AKIAIOSFODNN7EXAMPLE
  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
# ---------------------------- Minio ----------------------------

# ---------------------------- FileUpload ----------------------------
spring:
  servlet:
    multipart:
      #      是否支持 multipart 上传文件
      enabled: true
      #      最大支持请求大小
      max-request-size: 5MB
      #      最大支持文件大小
      max-file-size: 5MB

# ---------------------------- FileUpload ----------------------------
