spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: yatxuan@qq.com
    # 使用 jasypt 加密密码，使用com.yat.test.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password: ENC(GSu8uMgIZgMNIuNC7TZjHZO9qDtGTptAe6QP5K+AeMc=)
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: spring-boot-demo
# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: spring-boot-demo


task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
